version: '3'

services:
  safe-ed-base:
    build:
      context: .
    labels:
      author: "danX <chenxd@bankledger.com>"
      maintainer: "danX <chenxd@bankledger.com>"
      version: "2.0.0"
      description: "This is the base develop environment for compiling"
    image: dockerhub.bankledger.com/safe-ed-base:2.0.0-snapshot
    volumes:
      - ./mount/bankledger:/home/bankledger
      - ./mount/ex-work:/home/ex-work
#sample only
#    ports:
#      - "8081:8081"
