version: '3'

services:
  safe-env-dev:
    build:
      context: .
    labels:
      author: "danX <chenxd@bankledger.com>"
      maintainer: "danX <chenxd@bankledger.com>"
      version: "2.0.0"
      description: "This is the develop environment for compiling, deploying and running program bankledger.com/safe:^2.x.y"
    image: bankledger.com/safe-env-dev:2.0.0-snapshot
    volumes:
      - ./mount/bankledger:/home/bankledger
      - ./mount/ex-work:/home/ex-work
#sample only
#    ports:
#      - "8081:8081"
